name: Trigger scrape

on: 
  schedule:  
  - cron: '0 8 * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: npm install and run
      run: |
        npm install
        npm run scrape
